name = "web"
compatibility_date = "2024-03-29"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DATABASE"
database_name = "supermemory"
database_id = "f7e506c2-17d6-4a69-9dd1-56310fe03a76"

[[unsafe.bindings]]
name = "RATELIMITER"
type = "ratelimit"
namespace_id = "1001" 

# 25 requests per 10 seconds
simple = { limit = 25, period = 10 }

[placement]
mode = "smart"